Program for heart disease prediction AI/ML model

In [6]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, BaggingClassifier, VotingClassifier, AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_selection import SelectKBest, f_classif

Data collection and Pre-procesing

In [7]:
# loading our heart.csv file to a panda dataframe
heart_data = pd.read_csv('/content/heart.csv')
heart_data.shape

(1025, 14)

In [8]:
# getting some info about our dataset
heart_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

In [9]:
# statistical measure of our data
heart_data.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,1025.000000,1025.000000,1025.000000,1025.000000,1025.00000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000
mean,54.434146,0.695610,0.942439,131.611707,246.00000,0.149268,0.529756,149.114146,0.336585,1.071512,1.385366,0.754146,2.323902,0.513171
std,9.072290,0.460373,1.029641,17.516718,51.59251,0.356527,0.527878,23.005724,0.472772,1.175053,0.617755,1.030798,0.620660,0.500070
min,29.000000,0.000000,0.000000,94.000000,126.00000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.000000,0.000000,0.000000,120.000000,211.00000,0.000000,0.000000,132.000000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,56.000000,1.000000,1.000000,130.000000,240.00000,0.000000,1.000000,152.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,275.00000,0.000000,1.000000,166.000000,1.000000,1.800000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.00000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [10]:
# checking the distribution of target variable
heart_data['target'].value_counts()

target
1    526
0    499
Name: count, dtype: int64

In [11]:
# Data preprocessing
#1. Handling missing values
imputer = SimpleImputer(strategy='median')
heart_data_imputed = pd.DataFrame(imputer.fit_transform(heart_data), columns=heart_data.columns)

In [12]:
# Splitting features and target
X = heart_data_imputed.drop(columns='target', axis=1)
Y = heart_data_imputed['target']
print(X)
print(Y)

       age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0     52.0  1.0  0.0     125.0  212.0  0.0      1.0    168.0    0.0      1.0
1     53.0  1.0  0.0     140.0  203.0  1.0      0.0    155.0    1.0      3.1
2     70.0  1.0  0.0     145.0  174.0  0.0      1.0    125.0    1.0      2.6
3     61.0  1.0  0.0     148.0  203.0  0.0      1.0    161.0    0.0      0.0
4     62.0  0.0  0.0     138.0  294.0  1.0      1.0    106.0    0.0      1.9
...    ...  ...  ...       ...    ...  ...      ...      ...    ...      ...
1020  59.0  1.0  1.0     140.0  221.0  0.0      1.0    164.0    1.0      0.0
1021  60.0  1.0  0.0     125.0  258.0  0.0      0.0    141.0    1.0      2.8
1022  47.0  1.0  0.0     110.0  275.0  0.0      0.0    118.0    1.0      1.0
1023  50.0  0.0  0.0     110.0  254.0  0.0      0.0    159.0    0.0      0.0
1024  54.0  1.0  0.0     120.0  188.0  0.0      1.0    113.0    0.0      1.4

      slope   ca  thal
0       2.0  2.0   3.0
1       0.0  0.0   3.0
2       0.0  0.0   3.0
3       2.0  1.0   3.0
4       1.0  3.0   2.0
...     ...  ...   ...
1020    2.0  0.0   2.0
1021    1.0  1.0   3.0
1022    1.0  1.0   2.0
1023    2.0  0.0   2.0
1024    1.0  1.0   3.0

[1025 rows x 13 columns]
0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
       ...
1020    1.0
1021    0.0
1022    0.0
1023    1.0
1024    0.0
Name: target, Length: 1025, dtype: float64

In [13]:
#Feature scaling(Normalization)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print(X)

       age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0     52.0  1.0  0.0     125.0  212.0  0.0      1.0    168.0    0.0      1.0
1     53.0  1.0  0.0     140.0  203.0  1.0      0.0    155.0    1.0      3.1
2     70.0  1.0  0.0     145.0  174.0  0.0      1.0    125.0    1.0      2.6
3     61.0  1.0  0.0     148.0  203.0  0.0      1.0    161.0    0.0      0.0
4     62.0  0.0  0.0     138.0  294.0  1.0      1.0    106.0    0.0      1.9
...    ...  ...  ...       ...    ...  ...      ...      ...    ...      ...
1020  59.0  1.0  1.0     140.0  221.0  0.0      1.0    164.0    1.0      0.0
1021  60.0  1.0  0.0     125.0  258.0  0.0      0.0    141.0    1.0      2.8
1022  47.0  1.0  0.0     110.0  275.0  0.0      0.0    118.0    1.0      1.0
1023  50.0  0.0  0.0     110.0  254.0  0.0      0.0    159.0    0.0      0.0
1024  54.0  1.0  0.0     120.0  188.0  0.0      1.0    113.0    0.0      1.4

      slope   ca  thal
0       2.0  2.0   3.0
1       0.0  0.0   3.0
2       0.0  0.0   3.0
3       2.0  1.0   3.0
4       1.0  3.0   2.0
...     ...  ...   ...
1020    2.0  0.0   2.0
1021    1.0  1.0   3.0
1022    1.0  1.0   2.0
1023    2.0  0.0   2.0
1024    1.0  1.0   3.0

[1025 rows x 13 columns]

In [14]:
from sklearn.feature_selection import SelectKBest, f_classif
# automatic feature selection
print('Selecting best number of features using cross validation')
best_k = 0
best_score = 0

# Temporarily store the best selector found within the loop
final_selector_for_X_new = None

for k in range(5, X.shape[1] + 1):
   temp_selector = SelectKBest(score_func=f_classif, k=k)
   X_temp = temp_selector.fit_transform(X_scaled, Y)
   model_cv = LogisticRegression(max_iter=1000)
   scores = cross_val_score(model_cv, X_temp, Y, cv=10, scoring='f1')
   if scores.mean() > best_score:
     best_score = scores.mean()
     best_k = k
     final_selector_for_X_new = temp_selector # Store this selector if it leads to the best score

print(f'\n Best number of features (k): {best_k}')
print(f'\n Cross validated F1-score for best k: {best_score:.3f}')

# Initialize and fit the global 'selector' variable with the best_k found
# This ensures the 'selector' object used later for prediction has the correct configuration
selector = SelectKBest(score_func=f_classif, k=best_k)
X_new = selector.fit_transform(X_scaled, Y)

Selecting best number of features using cross validation

 Best number of features (k): 10

 Cross validated F1-score for best k: 0.866

In [15]:
# splitting data into training and testing data
X_train, X_test, Y_train, Y_test = train_test_split(X_new, Y, test_size=0.14, stratify=Y, random_state=2)
print (X.shape, X_train.shape, X_test.shape)
print(f'\nOriginal Shape: {X_scaled.shape}, Training Shape: {X_train.shape}, Testing Shape: {X_test.shape}')

(1025, 13) (881, 10) (144, 10)

Original Shape: (1025, 13), Training Shape: (881, 10), Testing Shape: (144, 10)

In [16]:
# Define models
log_reg = LogisticRegression(max_iter=1000, random_state=2)
dt_clf = DecisionTreeClassifier(max_depth=8, random_state=2)
rf_clf = RandomForestClassifier(n_estimators=200, random_state=2)
gb_clf = GradientBoostingClassifier(n_estimators=200, learning_rate = 0.05, random_state=2)
ada_clf = AdaBoostClassifier(n_estimators=200,learning_rate = 0.05, random_state=2)
# voting classifier combining major models
voting_clf = VotingClassifier(estimators=[('lr', log_reg), ('dt', dt_clf), ('rf', rf_clf), ('gb', gb_clf),], voting='soft')
models = {'Logistic Regression': log_reg, 'Decision Tree': dt_clf, 'Random Forest': rf_clf, 'Gradient Boosting': gb_clf, 'AdaBoost': ada_clf, 'Voting Classifier': voting_clf}

In [17]:
# Model Training
best_model = None
highest_f1 = -1
print('\n Training and evaluation results forall models')
for model_name, model in models.items():
#model_name = DecisionTreeClassifier()
 model.fit(X_train, Y_train)

 Training and evaluation results forall models

In [18]:
# Model evaluation
X_test_prediction = model.predict(X_test)

# accuracy score
# accuracy on Training data
X_train_prediction = model.predict(X_train)
accuracy_train = accuracy_score(X_train_prediction, Y_train)
print('Accuracy on Training data:', accuracy_train)

#accuracy on test data
X_test_prediction = model.predict(X_test)
accuracy_test = accuracy_score(Y_test, X_test_prediction)
#print('Accuracy on Test data:', accuracy_test)

#precision
precision_train = precision_score(X_train_prediction, Y_train)
print('Precision on training data:', precision_train)
precision_test = precision_score(Y_test, X_test_prediction)
#print('Precision on testing data:', precision_test)

#recall
recall_train = recall_score(X_train_prediction, Y_train)
print('Recall score of training data:', recall_train)
recall_test = recall_score(Y_test, X_test_prediction)
#print('Recall score of testing data:', recall_test)

#f1 score
f1_train = f1_score(X_train_prediction, Y_train)
print('F1 score of training data:', f1_train)
f1_test = f1_score(Y_test, X_test_prediction)
#print('F1 score of training data:', f1_test)

print(f'\n**{model_name}**')
print(f'Accuracy on testing data: {accuracy_test:.4f}')
print(f'Precision on testing data: {precision_test:.4f}')
print(f'Recall on testing data: {recall_test:.4f}')
print(f'F1 score on testing data: {f1_test:.4f}')
print(f'\nClassification Report for {model_name}:\n {classification_report(Y_test, X_test_prediction)}')
if f1_test > highest_f1:
  highest_f1 = f1_test
  best_model = model

Accuracy on Training data: 0.9931895573212258
Precision on training data: 0.995575221238938
Recall score of training data: 0.9911894273127754
F1 score of training data: 0.9933774834437086

**Voting Classifier**
Accuracy on testing data: 0.9931
Precision on testing data: 1.0000
Recall on testing data: 0.9865
F1 score on testing data: 0.9932

Classification Report for Voting Classifier:
               precision    recall  f1-score   support

         0.0       0.99      1.00      0.99        70
         1.0       1.00      0.99      0.99        74

    accuracy                           0.99       144
   macro avg       0.99      0.99      0.99       144
weighted avg       0.99      0.99      0.99       144

In [19]:
# Building a Predictive System
print('\n Enter the following details to predict heart disease')
feature_name = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal']
input_data = []
for feature in feature_name:
  value = float(input(f'Enter {feature}: '))
  input_data.append(value)
# change the input data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the numpy array as we are predicting for only one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
input_data_scaled = scaler.transform (input_data_reshaped)

# Apply feature selection to the input data
input_data_final = selector.transform(input_data_scaled)

prediction = best_model.predict(input_data_final)
print(prediction)

if(prediction[0] == 0):
  print('Your heart is healthy')
else:
  print('You have a heart disease')

 Enter the following details to predict heart disease

KeyboardInterrupt: Interrupted by user